name: climlab-courseware
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - xarray
  - metpy
  - cartopy
  - sympy
  - ffmpeg
  - jupyter
  - climlab>=0.7.11  # minimum version that uses pooch for data caching
  - numba>=0.43.1  # older version will hang forever under python 3, https://github.com/brian-rose/climlab/issues/101
  - netcdf4
  - nc-time-axis
