name: build-book
on:
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: climlab-courseware
          auto-update-conda: false
          python-version: 3.10
          environment-file: render-environment.yml
          mamba-version: '*'
          use-mamba: true
      - name: Build the book
        run: |
          jupyter-book build notebooks/
      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip notebooks/_build/html
      - name: Upload zipped book artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-zip-${{github.event.number}}
          path: ./book.zip
