name: delete-preview
on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set message value
        run: |
          echo "comment_message=👋 Thanks for opening this PR! The book will be automatically built with [GitHub Actions](https://github.com/features/actions). To see the status of your deployment, click below." >> $GITHUB_ENV

      - name: Remove book files
        run: |
          rm -rf _build/html/*

      - name: Delete deployed preview
        if: |
          github.event.pull_request.number != ''
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          enable_jekyll: false
          destination_dir: _preview/${{ github.event.pull_request.number }}
