name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'brian-rose/ClimateLaboratoryBook'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: book-render
          use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/book-render
          key: linux-64-conda-${{ hashFiles('book-render.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: mamba env update -n book-render -f render-environment.yml

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .
      # Push the book's HTML to github-pages
      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
