name: preview-book
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: github.repository == 'brian-rose/ClimateLaboratoryBook'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: climlab-courseware
          auto-update-conda: false
          python-version: 3.8
          environment-file: render-environment.yml
          mamba-version: '*'
          use-mamba: true

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .
      # Push the book's HTML to github-pages
      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          enable_jekyll: false
          destination_dir: _preview
