name: set-up-environment
# A reusable action, to be called from other actions
# This sets up the conda environment
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: climlab-courseware
          auto-update-conda: false
          python-version: 3.8
          environment-file: render-environment.yml
          mamba-version: '*'
          use-mamba: true
